/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coursework;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author leest
 */

public class BankApp extends javax.swing.JFrame {
    ArrayList<Account> accounts = Utility.readFile("Accounts.txt");
    Account currentAccount;
    
    private void initiateAccounts(){
    
    for(Account a : accounts){
        accountDropDown.addItem(a);
    }
    }
    /**
     * Creates new form BankApp
     */
    public BankApp() {
        initComponents();
        initiateAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        accountDropDown = new javax.swing.JComboBox<>();
        Exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Account Number:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 112, 14);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Account Holder:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 90, 14);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Open Date:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 190, 67, 14);

        customerField.setEditable(false);
        getContentPane().add(customerField);
        customerField.setBounds(130, 140, 144, 30);

        dateField.setEditable(false);
        getContentPane().add(dateField);
        dateField.setBounds(130, 190, 144, 30);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Balance:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 52, 14);

        balanceField.setEditable(false);
        getContentPane().add(balanceField);
        balanceField.setBounds(130, 240, 144, 30);

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositButton);
        depositButton.setBounds(300, 100, 86, 23);

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawButton);
        withdrawButton.setBounds(300, 150, 86, 23);

        Transfer.setText("Transfer");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(300, 190, 73, 23);

        accountDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountDropDownActionPerformed(evt);
            }
        });
        getContentPane().add(accountDropDown);
        accountDropDown.setBounds(130, 100, 144, 22);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(300, 240, 73, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\leest\\Documents\\coursework\\ulster.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void accountDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountDropDownActionPerformed
   currentAccount = (Account) accountDropDown.getSelectedItem();
   customerField.setText(currentAccount.getaccountHolder());
   dateField.setText(currentAccount.getOpenDate());
   balanceField.setText(String.valueOf(currentAccount.getBalance()));
    }//GEN-LAST:event_accountDropDownActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
     String amountString = JOptionPane.showInputDialog(this, "Enter amount to deposit: ", "Deposit", JOptionPane.PLAIN_MESSAGE);
     double amount = Double.parseDouble(amountString);
     currentAccount.deposit(amount);
     balanceField.setText(String.valueOf(currentAccount.getBalance()));
     Utility.writeFile(accounts,"Accounts.txt");
     
     
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
       String amountString = JOptionPane.showInputDialog(this, "Enter amount to Withdraw: ", "Withdraw", JOptionPane.PLAIN_MESSAGE);
     double amount = Double.parseDouble(amountString);
     currentAccount.withdraw(amount);
     balanceField.setText(String.valueOf(currentAccount.getBalance()));
     Utility.writeFile(accounts,"Accounts.txt");
     
     
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
    String accountNumber = JOptionPane.showInputDialog(this, "Enter an account to Transfer to: ", "Transfer", JOptionPane.PLAIN_MESSAGE);
    Account transferAccount = null;
    for(Account a : accounts){
        if(a.toString().equals(accountNumber)){
            transferAccount = a;
            break;
            
        }
    }
     
     String amountString = JOptionPane.showInputDialog(this, "Enter amount to Transfer: ", "Transfer", JOptionPane.PLAIN_MESSAGE);
     double amount = Double.parseDouble(amountString);
     if (transferAccount != null){
     currentAccount.transfer(transferAccount,amount);
     balanceField.setText(String.valueOf(currentAccount.getBalance()));
     Utility.writeFile(accounts,"Accounts.txt");
     
     }
    }//GEN-LAST:event_TransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankApp().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Transfer;
    private javax.swing.JComboBox<Account> accountDropDown;
    private javax.swing.JTextField balanceField;
    private javax.swing.JTextField customerField;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
